name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare SSH secret key
        run: |
          echo "${{ secrets.AUR_SSH_PRIV_KEY }}" > privkey
      - name: Prepare docker-compose.yaml
        run: |
          cat << EOF > docker-compose.yaml
            services:
              app:
                environment:
                  MAINTAINER: "${{ vars.MAINTAINER }}"
                  SLACK_TOKEN: "${{ secrets.SLACK_TOKEN }}"
                  SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
                  GIT_USER_NAME: "${{ vars.GIT_USER_NAME }}"
                  GIT_USER_EMAIL: "${{ secrets.GIT_USER_EMAIL }}"
                build:
                  context: .
                  dockerfile: Dockerfile
                image: local/update-pkgbuild-on-aur:latest
                restart: always
                network_mode: bridge
          EOF
      - name: Prepare containers
        run: docker compose build
      - name: Run containers
        run: docker compose up --exit-code-from app
